/home/jinyao/anaconda3/envs/IADBE/bin/python /home/jinyao/PycharmProjects/IADBE/train_test_btech_padim.py
2024-05-27 11:36:34,914 - INFO - ================== Processing dataset: 01 ==================
2024-05-27 11:36:34,914 - INFO - Initializing Padim model.
2024-05-27 11:36:35,115 - INFO - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
2024-05-27 11:36:35,183 - INFO - ================== Start training for dataset: 01 ==================
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2024-05-27 11:36:35,276 - INFO - Downloading the btech dataset.
btech: 1.23GB [00:49, 24.8MB/s]
2024-05-27 11:37:24,894 - INFO - Checking the hash of the downloaded file.
2024-05-27 11:37:25,913 - INFO - Extracting dataset into root folder.
2024-05-27 11:37:41,808 - INFO - Cleaning up files.
2024-05-27 11:37:41,909 - INFO - Renaming the dataset directory
2024-05-27 11:37:41,909 - INFO - Convert the bmp formats to png to have consistent image extensions
Converting bmp to png: 1952it [00:58, 33.58it/s]
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py:180: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer

  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | model                 | PadimModel               | 2.8 M
1 | _transform            | Compose                  | 0
2 | normalization_metrics | MinMax                   | 0
3 | image_threshold       | F1AdaptiveThreshold      | 0
4 | pixel_threshold       | F1AdaptiveThreshold      | 0
5 | image_metrics         | AnomalibMetricCollection | 0
6 | pixel_metrics         | AnomalibMetricCollection | 0
-------------------------------------------------------------------
2.8 M     Trainable params
0         Non-trainable params
2.8 M     Total params
11.131    Total estimated model params size (MB)
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
Epoch 0:   0%|          | 0/13 [00:00<?, ?it/s] /home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
Epoch 0:   8%|▊         | 1/13 [00:01<00:23,  0.51it/s]/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py:129: `training_step` returned `None`. If this was on purpose, ignore this warning...
Epoch 0: 100%|██████████| 13/13 [00:22<00:00,  0.59it/s]
Validation: |          | 0/? [00:00<?, ?it/s]2024-05-27 11:39:02,310 - INFO - Aggregating the embedding extracted from the training set.
2024-05-27 11:39:02,408 - INFO - Fitting a Gaussian to the embedding collected from the training set.

Validation:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0:  33%|███▎      | 1/3 [00:00<00:00, 10.19it/s]
Validation DataLoader 0:  67%|██████▋   | 2/3 [00:02<00:01,  0.97it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:02<00:00,  1.22it/s]
Epoch 0: 100%|██████████| 13/13 [00:31<00:00,  0.42it/s, pixel_AUROC=0.970, pixel_PRO=0.433]
`Trainer.fit` stopped: `max_epochs=1` reached.
2024-05-27 11:39:11,377 - INFO - Training took 31.20 seconds
2024-05-27 11:39:11,377 - INFO - ================== Start testing for dataset: 01 ==================
2024-05-27 11:39:11,446 - INFO - Found the dataset.
Restoring states from the checkpoint path at /home/jinyao/PycharmProjects/IADBE/results/Padim/BTech/01/v0/weights/lightning/model.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from the checkpoint at /home/jinyao/PycharmProjects/IADBE/results/Padim/BTech/01/v0/weights/lightning/model.ckpt
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
Testing DataLoader 0: 100%|██████████| 3/3 [00:15<00:00,  0.19it/s]
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        image_AUROC        │    0.9970844984054565     │
│         image_PRO         │            1.0            │
│        pixel_AUROC        │    0.9712724685668945     │
│         pixel_PRO         │    0.4328652024269104     │
└───────────────────────────┴───────────────────────────┘
2024-05-27 11:39:29,313 - INFO - Testing took 17.72285532951355 seconds
Throughput (batch_size=32) : 3.9497021613345944 FPS
2024-05-27 11:39:29,399 - INFO - ================== Processing dataset: 02 ==================
2024-05-27 11:39:29,399 - INFO - Initializing Padim model.
2024-05-27 11:39:29,602 - INFO - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
2024-05-27 11:39:29,669 - INFO - ================== Start training for dataset: 02 ==================
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2024-05-27 11:39:29,679 - INFO - Found the dataset.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py:180: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer

  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | model                 | PadimModel               | 2.8 M
1 | _transform            | Compose                  | 0
2 | normalization_metrics | MinMax                   | 0
3 | image_threshold       | F1AdaptiveThreshold      | 0
4 | pixel_threshold       | F1AdaptiveThreshold      | 0
5 | image_metrics         | AnomalibMetricCollection | 0
6 | pixel_metrics         | AnomalibMetricCollection | 0
-------------------------------------------------------------------
2.8 M     Trainable params
0         Non-trainable params
2.8 M     Total params
11.131    Total estimated model params size (MB)
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
Epoch 0: 100%|██████████| 13/13 [00:04<00:00,  3.23it/s]
Validation: |          | 0/? [00:00<?, ?it/s]2024-05-27 11:39:33,738 - INFO - Aggregating the embedding extracted from the training set.
2024-05-27 11:39:33,841 - INFO - Fitting a Gaussian to the embedding collected from the training set.

Validation:   0%|          | 0/8 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/8 [00:00<?, ?it/s]
Validation DataLoader 0:  12%|█▎        | 1/8 [00:00<00:00, 14.09it/s]
Validation DataLoader 0:  25%|██▌       | 2/8 [00:00<00:01,  4.11it/s]
Validation DataLoader 0:  38%|███▊      | 3/8 [00:00<00:01,  3.32it/s]
Validation DataLoader 0:  50%|█████     | 4/8 [00:01<00:01,  3.04it/s]
Validation DataLoader 0:  62%|██████▎   | 5/8 [00:01<00:01,  2.88it/s]
Validation DataLoader 0:  75%|███████▌  | 6/8 [00:02<00:00,  2.79it/s]
Validation DataLoader 0:  88%|████████▊ | 7/8 [00:02<00:00,  2.77it/s]
Validation DataLoader 0: 100%|██████████| 8/8 [00:02<00:00,  3.05it/s]
Epoch 0: 100%|██████████| 13/13 [00:14<00:00,  0.93it/s, pixel_AUROC=0.957, pixel_PRO=0.393]
`Trainer.fit` stopped: `max_epochs=1` reached.
2024-05-27 11:39:43,744 - INFO - Training took 14.03 seconds
2024-05-27 11:39:43,744 - INFO - ================== Start testing for dataset: 02 ==================
2024-05-27 11:39:43,816 - INFO - Found the dataset.
Restoring states from the checkpoint path at /home/jinyao/PycharmProjects/IADBE/results/Padim/BTech/02/v0/weights/lightning/model.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from the checkpoint at /home/jinyao/PycharmProjects/IADBE/results/Padim/BTech/02/v0/weights/lightning/model.ckpt
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
Testing DataLoader 0: 100%|██████████| 8/8 [00:34<00:00,  0.23it/s]
2024-05-27 11:40:18,492 - INFO - Testing took 34.526556968688965 seconds
Throughput (batch_size=32) : 6.661538832516074 FPS
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        image_AUROC        │    0.8726666569709778     │
│         image_PRO         │            1.0            │
│        pixel_AUROC        │     0.956802248954773     │
│         pixel_PRO         │    0.39256954193115234    │
└───────────────────────────┴───────────────────────────┘
2024-05-27 11:40:18,584 - INFO - ================== Processing dataset: 03 ==================
2024-05-27 11:40:18,584 - INFO - Initializing Padim model.
2024-05-27 11:40:18,779 - INFO - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
2024-05-27 11:40:18,842 - INFO - ================== Start training for dataset: 03 ==================
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2024-05-27 11:40:18,851 - INFO - Found the dataset.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py:180: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer

  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | model                 | PadimModel               | 2.8 M
1 | _transform            | Compose                  | 0
2 | normalization_metrics | MinMax                   | 0
3 | image_threshold       | F1AdaptiveThreshold      | 0
4 | pixel_threshold       | F1AdaptiveThreshold      | 0
5 | image_metrics         | AnomalibMetricCollection | 0
6 | pixel_metrics         | AnomalibMetricCollection | 0
-------------------------------------------------------------------
2.8 M     Trainable params
0         Non-trainable params
2.8 M     Total params
11.131    Total estimated model params size (MB)
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
Epoch 0: 100%|██████████| 32/32 [00:11<00:00,  2.73it/s]
Validation: |          | 0/? [00:00<?, ?it/s]2024-05-27 11:40:30,639 - INFO - Aggregating the embedding extracted from the training set.
2024-05-27 11:40:30,953 - INFO - Fitting a Gaussian to the embedding collected from the training set.

Validation:   0%|          | 0/14 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/14 [00:00<?, ?it/s]
Validation DataLoader 0:   7%|▋         | 1/14 [00:00<00:00, 13.85it/s]
Validation DataLoader 0:  14%|█▍        | 2/14 [00:00<00:03,  3.67it/s]
Validation DataLoader 0:  21%|██▏       | 3/14 [00:00<00:03,  3.17it/s]
Validation DataLoader 0:  29%|██▊       | 4/14 [00:01<00:03,  2.94it/s]
Validation DataLoader 0:  36%|███▌      | 5/14 [00:01<00:03,  2.84it/s]
Validation DataLoader 0:  43%|████▎     | 6/14 [00:02<00:02,  2.76it/s]
Validation DataLoader 0:  50%|█████     | 7/14 [00:02<00:02,  2.71it/s]
Validation DataLoader 0:  57%|█████▋    | 8/14 [00:03<00:02,  2.66it/s]
Validation DataLoader 0:  64%|██████▍   | 9/14 [00:03<00:01,  2.63it/s]
Validation DataLoader 0:  71%|███████▏  | 10/14 [00:03<00:01,  2.61it/s]
Validation DataLoader 0:  79%|███████▊  | 11/14 [00:04<00:01,  2.59it/s]
Validation DataLoader 0:  86%|████████▌ | 12/14 [00:04<00:00,  2.58it/s]
Validation DataLoader 0:  93%|█████████▎| 13/14 [00:05<00:00,  2.57it/s]
Validation DataLoader 0: 100%|██████████| 14/14 [00:05<00:00,  2.60it/s]
Epoch 0: 100%|██████████| 32/32 [00:31<00:00,  1.03it/s, pixel_AUROC=0.996, pixel_PRO=0.355]
`Trainer.fit` stopped: `max_epochs=1` reached.
2024-05-27 11:40:50,127 - INFO - Training took 31.23 seconds
2024-05-27 11:40:50,128 - INFO - ================== Start testing for dataset: 03 ==================
2024-05-27 11:40:50,224 - INFO - Found the dataset.
Restoring states from the checkpoint path at /home/jinyao/PycharmProjects/IADBE/results/Padim/BTech/03/v0/weights/lightning/model.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from the checkpoint at /home/jinyao/PycharmProjects/IADBE/results/Padim/BTech/03/v0/weights/lightning/model.ckpt
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
Testing DataLoader 0: 100%|██████████| 14/14 [01:05<00:00,  0.21it/s]
2024-05-27 11:41:56,182 - INFO - Testing took 65.78467082977295 seconds
Throughput (batch_size=32) : 6.703689392034039 FPS
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        image_AUROC        │     0.995670735836029     │
│         image_PRO         │            1.0            │
│        pixel_AUROC        │    0.9960825443267822     │
│         pixel_PRO         │    0.35456764698028564    │
└───────────────────────────┴───────────────────────────┘
