/bin/bash /home/jinyao/PycharmProjects/IADBE/train_test_kolektor_uflow.sh
(IADBE) jinyao@jinyao-System-Product-Name:~/PycharmProjects/IADBE$ /bin/bash /home/jinyao/PycharmProjects/IADBE/train_test_kolektor_uflow.sh
Running command: anomalib train --data anomalib.data.Kolektor --config ./configs/models/uflow.yaml
2024-06-25 12:28:46,817 - anomalib.utils.config - WARNING - Anomalib currently does not support multi-gpu training. Setting devices to 1.
[06/25/24 12:28:46] WARNING  Anomalib currently does not support multi-gpu training. Setting devices to 1.                                                                                                    config.py:262
2024-06-25 12:28:46,833 - anomalib.models.components.base.anomaly_module - INFO - Initializing Uflow model.
                    INFO     Initializing Uflow model.                                                                                                                                                 anomaly_module.py:42
2024-06-25 12:28:46,838 - anomalib.callbacks - INFO - Loading the callbacks
                    INFO     Loading the callbacks                                                                                                                                                           __init__.py:43
2024-06-25 12:28:46,839 - anomalib.engine.engine - INFO - Overriding num_sanity_val_steps from None with 0 for Uflow
                    INFO     Overriding num_sanity_val_steps from None with 0 for Uflow                                                                                                                        engine.py:84
2024-06-25 12:28:46,916 - lightning.pytorch.utilities.rank_zero - INFO - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[06/25/24 12:28:46] INFO     Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default               rank_zero.py:63
                             `ModelSummary` callback.
2024-06-25 12:28:46,924 - lightning.pytorch.utilities.rank_zero - INFO - GPU available: True (cuda), used: True
                    INFO     GPU available: True (cuda), used: True                                                                                                                                         rank_zero.py:63
2024-06-25 12:28:46,925 - lightning.pytorch.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
                    INFO     TPU available: False, using: 0 TPU cores                                                                                                                                       rank_zero.py:63
2024-06-25 12:28:46,925 - lightning.pytorch.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
                    INFO     IPU available: False, using: 0 IPUs                                                                                                                                            rank_zero.py:63
2024-06-25 12:28:46,926 - lightning.pytorch.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
                    INFO     HPU available: False, using: 0 HPUs                                                                                                                                            rank_zero.py:63
2024-06-25 12:28:46,927 - anomalib.data.image.kolektor - INFO - Found the dataset.
                    INFO     Found the dataset.                                                                                                                                                             kolektor.py:340
2024-06-25 12:28:46,969 - lightning.pytorch.utilities.rank_zero - INFO - You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
                    INFO     You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' |         rank_zero.py:63
                             'high')` which will trade-off precision for performance. For more details, read
                             https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2024-06-25 12:28:50,927 - timm.models.helpers - INFO - Loading pretrained weights from url (https://dl.fbaipublicfiles.com/deit/M48_448.pth)
[06/25/24 12:28:50] INFO     Loading pretrained weights from url (https://dl.fbaipublicfiles.com/deit/M48_448.pth)                                                                                           helpers.py:247
2024-06-25 12:28:52,616 - timm.models.helpers - INFO - Loading pretrained weights from url (https://dl.fbaipublicfiles.com/deit/S24_224.pth)
[06/25/24 12:28:52] INFO     Loading pretrained weights from url (https://dl.fbaipublicfiles.com/deit/S24_224.pth)                                                                                           helpers.py:247
2024-06-25 12:28:53,725 - lightning.pytorch.accelerators.cuda - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[06/25/24 12:28:53] INFO     LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]                                                                                                                                           cuda.py:58
┏━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃   ┃ Name                  ┃ Type                     ┃ Params ┃
┡━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ loss                  │ UFlowLoss                │      0 │
│ 1 │ _transform            │ Compose                  │      0 │
│ 2 │ normalization_metrics │ MinMax                   │      0 │
│ 3 │ image_threshold       │ F1AdaptiveThreshold      │      0 │
│ 4 │ pixel_threshold       │ F1AdaptiveThreshold      │      0 │
│ 5 │ image_metrics         │ AnomalibMetricCollection │      0 │
│ 6 │ pixel_metrics         │ AnomalibMetricCollection │      0 │
│ 7 │ model                 │ UflowModel               │  422 M │
└───┴───────────────────────┴──────────────────────────┴────────┘
Trainable params: 12.2 M
Non-trainable params: 409 M
Total params: 422 M
Total estimated model params size (MB): 1.7 K
/home/jinyao/anaconda3/envs/IADBE/lib/python3.10/site-packages/lightning/pytorch/core/module.py:494: You called `self.log('loss', ..., logger=True)` but have no logger configured. You can enable one by doing
`Trainer(logger=ALogger(...))`
Epoch 72/199 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 0:00:33 • 0:00:00 0.28it/s pixel_AUROC: 0.971 pixel_PRO: 0.2332024-06-25 13:39:37,353 - anomalib.callbacks.timer - INFO - Training took 4243.59 seconds
[06/25/24 13:39:37] INFO     Training took 4243.59 seconds                                                                                                                                                      timer.py:59
Epoch 72/199 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 0:00:33 • 0:00:00 0.28it/s pixel_AUROC: 0.970 pixel_PRO: 0.232
2024-06-25 13:39:37,358 - anomalib.data.image.kolektor - INFO - Found the dataset.
                    INFO     Found the dataset.                                                                                                                                                             kolektor.py:340
2024-06-25 13:39:37,752 - lightning.pytorch.accelerators.cuda - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[06/25/24 13:39:37] INFO     LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]                                                                                                                                           cuda.py:58
Testing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 0:00:27 • 0:00:00 0.12it/s  2024-06-25 13:40:14,027 - anomalib.callbacks.timer - INFO - Testing took 35.90082025527954 seconds
Throughput (batch_size=32) : 3.398251046424456 FPS
[06/25/24 13:40:14] INFO     Testing took 35.90082025527954 seconds                                                                                                                                            timer.py:109
                             Throughput (batch_size=32) : 3.398251046424456 FPS
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        image_AUROC        │    0.9090659618377686     │
│         image_PRO         │            1.0            │
│        pixel_AUROC        │    0.9704422950744629     │
│         pixel_PRO         │    0.23215144872665405    │
└───────────────────────────┴───────────────────────────┘
Testing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 0:00:27 • 0:00:00 0.12it/s